#!/usr/bin/env bash

# Configured for yabai v7.1.15

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist

# Dock settings
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0.5 # Takes 0.5 second for dock to show up
defaults write com.apple.dock no-bouncing -bool TRUE
defaults write com.apple.dock "autohide-time-modifier" -float "0.25"
defaults write com.apple.dock "tilesize" -int "36"
defaults write com.apple.dock "mineffect" -string "scale"

defaults write .GlobalPreferences _HIHideMenuBar -bool FALSE

# Load the yabai scripting addition (must add  yabai to sudoers first, check yabai docs)
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# General configurations
yabai -m config \
  debug_output on \
  window_animation_duration 0.0 \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist off \
  window_shadow float \
  window_opacity on \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_modifier alt \
  mouse_follows_focus on \
  focus_follows_mouse off \
  insert_feedback_color 0xffd75f5f \
  active_window_opacity 1.0 \
  normal_window_opacity 0.9

# Space padding
yabai -m config \
  top_padding 0 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 15

DEFAULT_SPACES=6
NUM_SPACES=$(yabai -m query --spaces | jq length)

# Create spaces
for ((i = 0; i < $((DEFAULT_SPACES - NUM_SPACES)); i++)); do
  yabai -m space --create
done

# Remove extra spaces
for ((i = 0; i < $((NUM_SPACES - DEFAULT_SPACES)); i++)); do
  yabai -m space last --destroy
done

# Float rules
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences' manage=off
yabai -m rule --add title='Settings' manage=off
yabai -m rule --add title='Help.*Slack' manage=off
yabai -m rule --add app='^Cisco AnyConnect Secure Mobility Client$' manage=off
yabai -m rule --add app='Cisco Secure Client' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='^$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Preferences' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Edit configuration' manage=off
yabai -m rule --add app='ACME' manage=off
yabai -m rule --add app='Todoist' title='Todoist' layer='above' is-sticky='true' manage=off

# Sticky rules
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add app='System Settings' sticky=on

# 1: Terminals
yabai -m rule --add app="Code" space=1
yabai -m rule --apply app="Code" space=1
# 2: Obsidian
yabai -m rule --add app="Obsidian" space=2
yabai -m rule --apply app="Obsidian" space=2
# 2: Browser
yabai -m rule --add app="Google Chrome" space=3
yabai -m rule --apply app="Google Chrome" space=3
# 3: Discord
yabai -m rule --add app="Discord" space=4
yabai -m rule --apply app="Discord" space=4
# 5: Zoom
yabai -m rule --add title=".*[Zz]oom.*" space=5
yabai -m rule --apply title=".*[Zz]oom.*" space=5
# 6: Spotify
yabai -m rule --add app="Spotify" space=6
yabai -m rule --apply app="Spotify" space=6

# Space layouts
yabai -m space 1 --layout stack
yabai -m space 2 --layout stack
yabai -m space 3 --layout bsp --balance
yabai -m space 4 --layout stack
yabai -m space 5 --layout stack
yabai -m space 6 --layout stack

# Focus each space to help apply rules and update sketchybar
yabai -m space --focus 6 && sleep 0.3
yabai -m space --focus 5 && sleep 0.3
yabai -m space --focus 4 && sleep 0.3
yabai -m space --focus 3 && sleep 0.3
yabai -m space --focus 2 && sleep 0.3
yabai -m space --focus 1

# When closing a window in a space, refocus the last window in that space
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus recent && yabai -m window --focus recent"

yabai -m signal --add event=space_changed action="nohup open -g raycast://extensions/krzysztoff1/yabai/screens-menu-bar?launchType=background > /dev/null 2>&1 &"
